services:
  db:
    container_name: db
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: notion
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - 55432:5432
    networks:
      - db_notion

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_PORT: 5050
    volumes:
      - pgadmin_working_dir:/var/lib/pgadmin
    ports:
      - 5050:5050
    networks:
      - db_notion

networks:
  db_notion:
    driver: bridge

volumes:
  pgadmin_working_dir:
    driver: local
  postgresql_data:
    driver: local
