name: Push image to GHCR
on:
  push:
    branches: [ master ]
  workflow_dispatch:
  
permissions:
  contents: read
  packages: write

env:
  IMAGE: ghcr.io/odaneo/notion.sync.api
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ./Notion.Sync.Api
          file: ./Notion.Sync.Api/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ github.sha }}
  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on EC2 (pull & restart)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_SSH_PORT || 22 }}
          script: |
            set -euo pipefail
            cd ~
            docker compose pull notion-sync-api
            docker compose up -d notion-sync-api --remove-orphans
            docker image prune -f
            docker ps --filter "name=notion-sync-api" --format "table {{.Names}}\t{{.Image}}\t{{.Status}}"
