name: Push image to GHCR
on:
  push:
    branches: [ master ]
  workflow_dispatch:
  
permissions:
  contents: read
  packages: write

env:
  IMAGE: ghcr.io/odaneo/notion.sync.api
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Notion.Sync.Api/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ github.sha }}
